# auto-generated by gen_entity.py — do not edit by hand
from .it_driver_license import IT_DRIVER_LICENSE
from .it_fiscal_code import IT_FISCAL_CODE
from .it_identity_card import IT_IDENTITY_CARD
from .it_passport import IT_PASSPORT
from .it_vat_code import IT_VAT_CODE

IT = [IT_DRIVER_LICENSE, IT_FISCAL_CODE, IT_IDENTITY_CARD, IT_PASSPORT, IT_VAT_CODE]

__all__ = [
    "IT_DRIVER_LICENSE",
    "IT_FISCAL_CODE",
    "IT_IDENTITY_CARD",
    "IT_PASSPORT",
    "IT_VAT_CODE",
    "IT",
]
