"""Maintain entities/__init__.py files after codegen writes or updates entity files.

Change this file when the __init__.py structure, block-marker format, or country-list
naming convention changes.
"""
import re
import sys
from pathlib import Path

_ENTITY_VAR_RE = re.compile(r'^([A-Z][A-Z0-9_]*)\s*=\s*Entity\(', re.MULTILINE)
_GEN_BLOCK_RE = re.compile(r'([ \t]*)# BEGIN GENERATED: (\w+)\n(.*?)\n\1# END GENERATED: \2', re.DOTALL)


def update_gen_blocks(old_source: str, new_source: str) -> str:
    """Splice GEN blocks from new_source into old_source, leaving everything else untouched.

    Falls back to full replacement when no old block names match the new source
    (e.g. after a block rename), so migration is automatic.
    """
    new_blocks = {m.group(2): m.group(0) for m in _GEN_BLOCK_RE.finditer(new_source)}
    old_names = {m.group(2) for m in _GEN_BLOCK_RE.finditer(old_source)}
    if old_names - new_blocks.keys():  # stale block names → migrate via full replacement
        return new_source
    return _GEN_BLOCK_RE.sub(
        lambda m: new_blocks.get(m.group(2), m.group(0)),
        old_source,
    )


def _find_entity_exports(path: Path) -> list[str]:
    return _ENTITY_VAR_RE.findall(path.read_text(encoding="utf-8"))


def refresh_country_init(directory: Path) -> bool:
    """Generate or overwrite __init__.py for a country entity subdirectory.

    Scans all .py files in the directory, collects Entity variable names, and
    writes a clean __init__.py with imports, a country list, and __all__.
    Returns True when the file is newly created (so the caller can register the new subpackage).
    """
    exports: list[tuple[str, str]] = []
    for py_file in sorted(directory.glob("*.py")):
        if py_file.name == "__init__.py":
            continue
        for var in _find_entity_exports(py_file):
            exports.append((py_file.stem, var))

    if not exports:
        return False

    init_path = directory / "__init__.py"
    was_new = not init_path.exists()

    all_vars = [var for _, var in exports]
    # Derive 2-letter code from the common entity prefix (e.g. AU_ABN → AU).
    # Fall back to the directory name uppercased if no underscore prefix exists.
    first_prefix = all_vars[0].split("_")[0] if all_vars else ""
    list_name = first_prefix if len(first_prefix) == 2 else directory.name.upper()

    lines = ["# auto-generated by gen_entity.py — do not edit by hand"]
    for module, var in exports:
        lines.append(f"from .{module} import {var}")
    lines.append("")
    lines.append(f"{list_name} = [{', '.join(all_vars)}]")
    lines.append("")
    lines.append("__all__ = [")
    for var in all_vars:
        lines.append(f'    "{var}",')
    lines.append(f'    "{list_name}",')
    lines.append("]")

    init_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return was_new


def refresh_root_init(entities_root: Path, new_packages: set[str]) -> None:
    """Add missing country subpackage imports to the root entities __init__.py."""
    if not new_packages:
        return
    init_path = entities_root / "__init__.py"
    if not init_path.exists():
        return
    content = init_path.read_text(encoding="utf-8")
    already = set(re.findall(r'from \. import (\w+)', content))
    missing = sorted(new_packages - already)
    if not missing:
        return

    lines = content.splitlines()
    last_import_idx = max(
        (i for i, ln in enumerate(lines) if ln.startswith("from . import ")),
        default=-1,
    )
    lines[last_import_idx + 1:last_import_idx + 1] = [f"from . import {pkg}" for pkg in missing]

    all_start = next((i for i, ln in enumerate(lines) if ln.strip() == "__all__ = ["), None)
    if all_start is not None:
        close = next(i for i in range(all_start, len(lines)) if lines[i].strip() == "]")
        lines[close:close] = [f'    "{pkg}",' for pkg in missing]

    init_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"updated entities/__init__.py with: {', '.join(missing)}", file=sys.stderr)
