# auto-generated by gen_entity.py — do not edit by hand
from .ng_nin import NG_NIN
from .ng_vehicle_registration import NG_VEHICLE_REGISTRATION

__all__ = [
    "NG_NIN",
    "NG_VEHICLE_REGISTRATION",
]
