# auto-generated by gen_entity.py — do not edit by hand
from .uk_nhs import UK_NHS
from .uk_nino import UK_NINO
from .uk_passport import UK_PASSPORT
from .uk_postcode import UK_POSTCODE
from .uk_vehicle_registration import UK_VEHICLE_REGISTRATION

UK = [UK_NHS, UK_NINO, UK_PASSPORT, UK_POSTCODE, UK_VEHICLE_REGISTRATION]

__all__ = [
    "UK_NHS",
    "UK_NINO",
    "UK_PASSPORT",
    "UK_POSTCODE",
    "UK_VEHICLE_REGISTRATION",
    "UK",
]
